# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-25 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analityc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='event_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener.ShortSURL'),
        ),
    ]
