# Generated by Django 2.2 on 2019-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analityc', '0002_auto_20190426_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='event_url',
            field=models.OneToOneField(on_delete=None, to='shortener.ShortSURL'),
        ),
    ]
