# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-24 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20190424_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortsurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
